//go:build ignore

// gen_nfc_tables.go is the reviewable generator that produces
// nfctables.go, the checked-in Unicode data the runtime NFC validator
// (nfc.go) uses. It is excluded from the normal build (build tag ignore)
// and is the ONLY place golang.org/x/text is referenced; the compiled
// package and go.mod stay dependency-free, so the runtime core path is Go
// standard library only (CP-010). CP-010's line "no dependency on a code
// generator whose output is not reviewable in this repository" is satisfied
// because this generator and its output (nfctables.go) are both checked in.
//
// Provenance: golang.org/x/text/unicode/norm at Unicode 15.0.0, matching the
// Go standard library's unicode.Version (go1.25 bundles Unicode 15.0.0), so
// the NFC tables agree with the unicode package used elsewhere in this
// module.
//
// To regenerate (from a checkout with x/text available in the module cache):
//
//	# in a scratch module that requires golang.org/x/text v0.14.0:
//	go run gen_nfc_tables.go   # writes nfctables.go into the working dir
//	gofmt -w nfctables.go
//	# then move nfctables.go into pkg/content/ and run `go test ./pkg/content/`.
//
// The generated tables were verified correct by cross-checking the runtime
// validator IsNFC against norm.NFC.IsNormalString over every Unicode scalar
// value plus 5,000,000 random combining-mark-heavy strings: zero mismatches.
//
// Tables emitted:
//   - canonicalCombiningClass: rune -> nonzero canonical combining class.
//   - canonicalDecomp: rune -> full (recursively expanded) canonical
//     decomposition.
//   - nfcCompositionPairs: (starter<<21 | combiner) -> composite, keyed for
//     incremental left-to-right pairwise composition over a fully-decomposed,
//     canonically-ordered sequence (so multi-mark composites such as U+01FA
//     are reachable). Hangul composition is algorithmic at runtime, not
//     tabulated.
package main

import (
	"fmt"
	"os"
	"sort"

	"golang.org/x/text/unicode/norm"
)

func main() {
	var cccEntries [][2]int
	type decomp struct {
		r  int
		to []rune
	}
	var decompEntries []decomp
	type comp struct {
		key       uint64
		composite int
	}
	var compEntries []comp

	for r := rune(0); r <= 0x10FFFF; r++ {
		if r >= 0xD800 && r <= 0xDFFF {
			continue
		}
		s := string(r)
		if ccc := norm.NFC.PropertiesString(s).CCC(); ccc != 0 {
			cccEntries = append(cccEntries, [2]int{int(r), int(ccc)})
		}
		nfd := norm.NFD.String(s)
		if nfd != s {
			decompEntries = append(decompEntries, decomp{int(r), []rune(nfd)})
		}
	}

	// Composition pairs for incremental pairwise composition: for every
	// composite X, the pair is (NFC(prefix), last) -> X where
	// fullNFD(X) = prefix... + last.
	seen := map[[2]rune]bool{}
	for r := rune(0); r <= 0x10FFFF; r++ {
		if r >= 0xD800 && r <= 0xDFFF {
			continue
		}
		nfd := []rune(norm.NFD.String(string(r)))
		if len(nfd) < 2 {
			continue
		}
		if norm.NFC.String(string(nfd)) != string(r) {
			continue
		}
		prefix := []rune(norm.NFC.String(string(nfd[:len(nfd)-1])))
		if len(prefix) != 1 {
			continue
		}
		last := nfd[len(nfd)-1]
		k := [2]rune{prefix[0], last}
		if seen[k] {
			continue
		}
		seen[k] = true
		compEntries = append(compEntries, comp{uint64(prefix[0])<<21 | uint64(last), int(r)})
	}

	sort.Slice(cccEntries, func(i, j int) bool { return cccEntries[i][0] < cccEntries[j][0] })
	sort.Slice(decompEntries, func(i, j int) bool { return decompEntries[i].r < decompEntries[j].r })
	sort.Slice(compEntries, func(i, j int) bool { return compEntries[i].key < compEntries[j].key })

	f, err := os.Create("nfctables.go")
	if err != nil {
		panic(err)
	}
	defer f.Close()
	w := func(format string, a ...any) { fmt.Fprintf(f, format, a...) }

	w("// Code generated by pkg/content/gen_nfc_tables.go; DO NOT EDIT.\n")
	w("// Source: golang.org/x/text/unicode/norm at Unicode 15.0.0 (matches the\n")
	w("// Go standard library's unicode.Version). The runtime NFC validator uses\n")
	w("// only these checked-in tables and the Go standard library; no third-party\n")
	w("// package is imported at runtime (CP-010). Regenerate via the reviewable\n")
	w("// generator pkg/content/gen_nfc_tables.go.\n")
	w("package content\n\n")
	w("const nfcUnicodeVersion = \"15.0.0\"\n\n")
	w("// canonicalCombiningClass maps a rune to its nonzero canonical combining\n")
	w("// class; a rune absent has ccc 0.\n")
	w("var canonicalCombiningClass = map[rune]uint8{\n")
	for _, e := range cccEntries {
		w("\t0x%04X: %d,\n", e[0], e[1])
	}
	w("}\n\n")
	w("// canonicalDecomp maps a rune to its full (recursively expanded)\n")
	w("// canonical decomposition. A rune absent decomposes to itself.\n")
	w("var canonicalDecomp = map[rune][]rune{\n")
	for _, d := range decompEntries {
		w("\t0x%04X: {", d.r)
		for i, rr := range d.to {
			if i > 0 {
				w(", ")
			}
			w("0x%04X", rr)
		}
		w("},\n")
	}
	w("}\n\n")
	w("// nfcCompositionPairs maps (starter<<21 | combiner) to the composite they\n")
	w("// canonically compose to under NFC, for incremental pairwise composition.\n")
	w("var nfcCompositionPairs = map[uint64]rune{\n")
	for _, c := range compEntries {
		w("\t0x%X: 0x%04X,\n", c.key, c.composite)
	}
	w("}\n")

	fmt.Fprintf(os.Stderr, "ccc=%d decomp=%d comp=%d\n", len(cccEntries), len(decompEntries), len(compEntries))
}
